version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
  
    steps:
      - checkout
      - run:
          environment:
            NG_CLI_ANALYTICS: "ci"
          command: npm install
      - run: npm install
      - run: cd ./angular-tour-of-heroes && sudo npm install -g @angular/cli && ng test
      - run: curl -X POST -d {} ${hook}
workflows:
    build-and-test:
      jobs:
        - build-and-test
