version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    working_directory: ~/angularJSTutorial
    docker:
      - image: circleci/node:12.18.0-browsers
    executor:
      name: node/default
  
    steps:
      - checkout
      - restore_cache:
          key: angularJSTutorial-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies from package-lock.json
          command: npm install
      - save_cache:
          key: angularJSTutorial-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Downgrade ChromeDriver ver 84 to ver 83 for e2e testing
          command: npm install chromedriver@83
      - run:
          name: Check Code Coverage and Run Unit and Integration tests
          command: npm run test -- --no-watch --no-progress --code-coverage --browsers ChromeHeadless
      - run:
          name: Run e2e tests
          command: npm run e2e -- --protractor-config=e2e/protractor.conf.js
      - run: 
          name: Deploy to Netlify through web hooks 
          command: curl -X POST -d {} ${hook}
workflows:
    build-test-deploy:
      jobs:
        - build-test-deploy
