version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.6.0-browsers
    executor:
      name: node/default
  
    steps:
      - checkout
      - run: 
          name: List current directory (For Debugging Purposes)
          command: ls -a
      - run: 
          name: Install dependencies from package-lock.json
          command: npm install
      - run:
          name: Set Environment
          command: echo 'export NG_CLI_ANALYTICS=ci' >> $BASH_ENV
      - run: 
          name: Install Angular CLI
          command: sudo npm install -g @angular/cli
      - run: 
          name: Run Unit Tests and Integration Tests
          command: ng test
      - run: 
          name: Deploy to Netlify through web hooks 
          command: curl -X POST -d {} ${hook}
workflows:
    build-and-test:
      jobs:
        - build-and-test
