version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Change Directory
                command: cd ./angular-tour-of-heroes
            - run:
                name: Install libs
                command: sudo apt-get install libxtst6 libgconf-2-4 libnss3 libasound2 libgtk-3-0 libxss1
            - run: npm install
            - run: npm run e2e
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
